// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CvtColor_1_16_0_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [11:0] j_reg_124;
reg    ap_sig_bdd_48;
wire   [11:0] i_1_fu_141_p2;
reg   [11:0] i_1_reg_265;
wire   [0:0] exitcond3_fu_147_p2;
reg   [0:0] exitcond3_reg_270;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_72;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_270_pp0_it6;
reg    ap_sig_bdd_90;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_270_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_270_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_270_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_270_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond3_reg_270_pp0_it5;
wire   [11:0] j_1_fu_152_p2;
reg   [7:0] tmp_45_reg_279;
reg   [7:0] tmp_46_reg_284;
reg   [7:0] ap_reg_ppstg_tmp_46_reg_284_pp0_it2;
reg   [7:0] tmp_47_reg_289;
wire   [26:0] grp_fu_161_p2;
reg   [26:0] r_V_reg_309;
wire   [27:0] grp_fu_170_p2;
reg   [27:0] rhs_V_cast_reg_314;
wire   [27:0] r_V_1_fu_188_p2;
reg   [27:0] r_V_1_reg_319;
wire   [28:0] grp_fu_179_p2;
reg   [28:0] rhs_V_1_cast_reg_324;
reg   [7:0] tmp_31_reg_329;
reg   [0:0] qbit_reg_334;
wire   [0:0] exitcond4_fu_136_p2;
reg   [11:0] i_reg_113;
wire   [7:0] grp_fu_161_p0;
wire   [17:0] grp_fu_161_p1;
wire   [7:0] grp_fu_170_p0;
wire   [19:0] grp_fu_170_p1;
wire   [7:0] grp_fu_179_p0;
wire   [20:0] grp_fu_179_p1;
wire   [27:0] lhs_V_cast_fu_185_p1;
wire   [28:0] lhs_V_1_cast_fu_193_p1;
wire   [28:0] r_V_2_fu_196_p2;
wire   [8:0] p_Val2_5_cast_fu_219_p1;
wire   [8:0] tmp_7_i_cast_fu_222_p1;
wire   [8:0] p_Val2_s_fu_225_p2;
wire   [0:0] tmp_43_fu_231_p3;
wire   [7:0] tmp_44_fu_239_p1;
reg    grp_fu_161_ce;
reg    grp_fu_170_ce;
reg    grp_fu_179_ce;
reg   [1:0] ap_NS_fsm;
wire   [26:0] grp_fu_161_p00;
wire   [27:0] grp_fu_170_p00;
wire   [28:0] grp_fu_179_p00;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_ST_st11_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv27_3A5E3 = 27'b111010010111100011;
parameter    ap_const_lv28_99168 = 28'b10011001000101101000;
parameter    ap_const_lv29_12C8B4 = 29'b100101100100010110100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_true = 1'b1;


image_filter_mul_8ns_18ns_27_3 #(
    .ID( 42 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 27 ))
image_filter_mul_8ns_18ns_27_3_U42(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_161_p0 ),
    .din1( grp_fu_161_p1 ),
    .ce( grp_fu_161_ce ),
    .dout( grp_fu_161_p2 )
);

image_filter_mul_8ns_20ns_28_3 #(
    .ID( 43 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 28 ))
image_filter_mul_8ns_20ns_28_3_U43(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_170_p0 ),
    .din1( grp_fu_170_p1 ),
    .ce( grp_fu_170_ce ),
    .dout( grp_fu_170_p2 )
);

image_filter_mul_8ns_21ns_29_3 #(
    .ID( 44 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 21 ),
    .dout_WIDTH( 29 ))
image_filter_mul_8ns_21ns_29_3_U44(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_179_p0 ),
    .din1( grp_fu_179_p1 ),
    .ce( grp_fu_179_ce ),
    .dout( grp_fu_179_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_147_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (exitcond3_fu_147_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_147_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
            ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st11_fsm_3 == ap_CS_fsm)) begin
        i_reg_113 <= i_1_reg_265;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_48)) begin
        i_reg_113 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (exitcond3_fu_147_p2 == ap_const_lv1_0))) begin
        j_reg_124 <= j_1_fu_152_p2;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
        j_reg_124 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_exitcond3_reg_270_pp0_it1 <= exitcond3_reg_270;
        ap_reg_ppstg_exitcond3_reg_270_pp0_it2 <= ap_reg_ppstg_exitcond3_reg_270_pp0_it1;
        ap_reg_ppstg_exitcond3_reg_270_pp0_it3 <= ap_reg_ppstg_exitcond3_reg_270_pp0_it2;
        ap_reg_ppstg_exitcond3_reg_270_pp0_it4 <= ap_reg_ppstg_exitcond3_reg_270_pp0_it3;
        ap_reg_ppstg_exitcond3_reg_270_pp0_it5 <= ap_reg_ppstg_exitcond3_reg_270_pp0_it4;
        ap_reg_ppstg_exitcond3_reg_270_pp0_it6 <= ap_reg_ppstg_exitcond3_reg_270_pp0_it5;
        ap_reg_ppstg_tmp_46_reg_284_pp0_it2 <= tmp_46_reg_284;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        exitcond3_reg_270 <= exitcond3_fu_147_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_1_reg_265 <= i_1_fu_141_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it5))) begin
        qbit_reg_334 <= r_V_2_fu_196_p2[ap_const_lv32_14];
        tmp_31_reg_329 <= {{r_V_2_fu_196_p2[ap_const_lv32_1C : ap_const_lv32_15]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it4))) begin
        r_V_1_reg_319 <= r_V_1_fu_188_p2;
        rhs_V_1_cast_reg_324 <= grp_fu_179_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it3))) begin
        r_V_reg_309 <= grp_fu_161_p2;
        rhs_V_cast_reg_314 <= grp_fu_170_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_270 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        tmp_45_reg_279 <= p_src_data_stream_0_V_dout;
        tmp_46_reg_284 <= p_src_data_stream_1_V_dout;
        tmp_47_reg_289 <= p_src_data_stream_2_V_dout;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or exitcond4_fu_136_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_136_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond4_fu_136_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond4_fu_136_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// grp_fu_161_ce assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond3_reg_270_pp0_it1 or ap_reg_ppstg_exitcond3_reg_270_pp0_it2 or ap_reg_ppstg_exitcond3_reg_270_pp0_it3)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it3)))) begin
        grp_fu_161_ce = ap_const_logic_1;
    end else begin
        grp_fu_161_ce = ap_const_logic_0;
    end
end

/// grp_fu_170_ce assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond3_reg_270_pp0_it1 or ap_reg_ppstg_exitcond3_reg_270_pp0_it2 or ap_reg_ppstg_exitcond3_reg_270_pp0_it3)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it1) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it3)))) begin
        grp_fu_170_ce = ap_const_logic_1;
    end else begin
        grp_fu_170_ce = ap_const_logic_0;
    end
end

/// grp_fu_179_ce assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_exitcond3_reg_270_pp0_it2 or ap_reg_ppstg_exitcond3_reg_270_pp0_it3 or ap_reg_ppstg_exitcond3_reg_270_pp0_it4)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ((ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it2) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it3) | (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it4)))) begin
        grp_fu_179_ce = ap_const_logic_1;
    end else begin
        grp_fu_179_ce = ap_const_logic_0;
    end
end

/// p_dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond3_reg_270_pp0_it6 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond3_reg_270 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_270 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or exitcond3_reg_270 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_270 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or exitcond3_reg_270 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond3_reg_270 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_48 or exitcond3_fu_147_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_72 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it6 or ap_sig_bdd_90 or ap_reg_ppiten_pp0_it7 or exitcond4_fu_136_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_48) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond4_fu_136_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if ((~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_147_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_72 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_90 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(exitcond3_fu_147_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st11_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_st11_fsm_3 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_48 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_48 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_72 assign process. ///
always @ (p_src_data_stream_0_V_empty_n or p_src_data_stream_1_V_empty_n or p_src_data_stream_2_V_empty_n or exitcond3_reg_270)
begin
    ap_sig_bdd_72 = (((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond3_reg_270 == ap_const_lv1_0)) | ((exitcond3_reg_270 == ap_const_lv1_0) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond3_reg_270 == ap_const_lv1_0) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)));
end

/// ap_sig_bdd_90 assign process. ///
always @ (p_dst_data_stream_0_V_full_n or ap_reg_ppstg_exitcond3_reg_270_pp0_it6)
begin
    ap_sig_bdd_90 = ((p_dst_data_stream_0_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond3_reg_270_pp0_it6));
end
assign exitcond3_fu_147_p2 = (j_reg_124 == p_src_cols_V_read? 1'b1: 1'b0);
assign exitcond4_fu_136_p2 = (i_reg_113 == p_src_rows_V_read? 1'b1: 1'b0);
assign grp_fu_161_p0 = grp_fu_161_p00;
assign grp_fu_161_p00 = $unsigned(tmp_45_reg_279);
assign grp_fu_161_p1 = ap_const_lv27_3A5E3;
assign grp_fu_170_p0 = grp_fu_170_p00;
assign grp_fu_170_p00 = $unsigned(tmp_47_reg_289);
assign grp_fu_170_p1 = ap_const_lv28_99168;
assign grp_fu_179_p0 = grp_fu_179_p00;
assign grp_fu_179_p00 = $unsigned(ap_reg_ppstg_tmp_46_reg_284_pp0_it2);
assign grp_fu_179_p1 = ap_const_lv29_12C8B4;
assign i_1_fu_141_p2 = (i_reg_113 + ap_const_lv12_1);
assign j_1_fu_152_p2 = (j_reg_124 + ap_const_lv12_1);
assign lhs_V_1_cast_fu_193_p1 = $unsigned(r_V_1_reg_319);
assign lhs_V_cast_fu_185_p1 = $unsigned(r_V_reg_309);
assign p_Val2_5_cast_fu_219_p1 = $unsigned(tmp_31_reg_329);
assign p_Val2_s_fu_225_p2 = (p_Val2_5_cast_fu_219_p1 + tmp_7_i_cast_fu_222_p1);
assign p_dst_data_stream_0_V_din = ((tmp_43_fu_231_p3)? ap_const_lv8_FF: tmp_44_fu_239_p1);
assign r_V_1_fu_188_p2 = (rhs_V_cast_reg_314 + lhs_V_cast_fu_185_p1);
assign r_V_2_fu_196_p2 = (rhs_V_1_cast_reg_324 + lhs_V_1_cast_fu_193_p1);
assign tmp_43_fu_231_p3 = p_Val2_s_fu_225_p2[ap_const_lv32_8];
assign tmp_44_fu_239_p1 = p_Val2_s_fu_225_p2[7:0];
assign tmp_7_i_cast_fu_222_p1 = $unsigned(qbit_reg_334);


endmodule //CvtColor_1_16_0_1080_1920_s

