// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Dilate_0_0_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_dst_data_stream_0_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
wire    grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_done;
reg   [7:0] temp_kernel_val_0_0_reg_115;
reg   [7:0] temp_kernel_val_0_1_reg_120;
reg   [7:0] temp_kernel_val_0_2_reg_125;
reg   [7:0] temp_kernel_val_1_0_reg_130;
reg   [7:0] temp_kernel_val_1_1_reg_135;
reg   [7:0] temp_kernel_val_1_2_reg_140;
reg   [7:0] temp_kernel_val_2_0_reg_145;
reg   [7:0] temp_kernel_val_2_1_reg_150;
reg   [7:0] temp_kernel_val_2_2_reg_155;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_idle;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_ready;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_dout;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_empty_n;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_din;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_full_n;
wire    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_write;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_0_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_1_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_2_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_0_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_1_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_2_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_0_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_1_read;
wire   [7:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_2_read;
wire   [11:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_rows;
wire   [11:0] grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_cols;
wire    grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start;
wire    grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_idle;
wire    grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_ready;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_0;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_1;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_2;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_3;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_4;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_5;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_6;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_7;
wire   [7:0] grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_8;
reg    grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg = 1'b0;
reg    grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_bdd_105;
reg   [1:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_st3_fsm_2 = 2'b10;
parameter    ap_true = 1'b1;


filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start ),
    .ap_done( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done ),
    .ap_idle( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_idle ),
    .ap_ready( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_ready ),
    .p_src_data_stream_0_V_dout( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_read ),
    .p_dst_data_stream_0_V_din( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_din ),
    .p_dst_data_stream_0_V_full_n( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_full_n ),
    .p_dst_data_stream_0_V_write( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_write ),
    .kernel_val_0_0_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_0_read ),
    .kernel_val_0_1_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_1_read ),
    .kernel_val_0_2_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_2_read ),
    .kernel_val_1_0_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_0_read ),
    .kernel_val_1_1_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_1_read ),
    .kernel_val_1_2_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_2_read ),
    .kernel_val_2_0_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_0_read ),
    .kernel_val_2_1_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_1_read ),
    .kernel_val_2_2_read( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_2_read ),
    .rows( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_rows ),
    .cols( grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_cols )
);

getStructuringElement_unsigned_char_int_int_3_3_s grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start ),
    .ap_done( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_done ),
    .ap_idle( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_idle ),
    .ap_ready( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_ready ),
    .ap_return_0( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_0 ),
    .ap_return_1( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_1 ),
    .ap_return_2( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_2 ),
    .ap_return_3( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_3 ),
    .ap_return_4( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_4 ),
    .ap_return_5( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_5 ),
    .ap_return_6( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_6 ),
    .ap_return_7( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_7 ),
    .ap_return_8( grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_8 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_done))) begin
            grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_ready)) begin
            grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_105)) begin
            grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_ready)) begin
            grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_done))) begin
        temp_kernel_val_0_0_reg_115 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_0;
        temp_kernel_val_0_1_reg_120 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_1;
        temp_kernel_val_0_2_reg_125 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_2;
        temp_kernel_val_1_0_reg_130 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_3;
        temp_kernel_val_1_1_reg_135 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_4;
        temp_kernel_val_1_2_reg_140 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_5;
        temp_kernel_val_2_0_reg_145 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_6;
        temp_kernel_val_2_1_reg_150 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_7;
        temp_kernel_val_2_2_reg_155 <= grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_return_8;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(ap_const_logic_0 == grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// p_dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_write)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        p_dst_data_stream_0_V_write = grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_write;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_read)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        p_src_data_stream_0_V_read = grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_read;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_done or grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done or ap_sig_bdd_105)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_105) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_logic_0 == grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st3_fsm_2 : 
            if (~(ap_const_logic_0 == grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_105 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_105 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start = grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_ap_start_ap_start_reg;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_cols = p_src_cols_V_read;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_0_read = temp_kernel_val_0_0_reg_115;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_1_read = temp_kernel_val_0_1_reg_120;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_0_2_read = temp_kernel_val_0_2_reg_125;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_0_read = temp_kernel_val_1_0_reg_130;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_1_read = temp_kernel_val_1_1_reg_135;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_1_2_read = temp_kernel_val_1_2_reg_140;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_0_read = temp_kernel_val_2_0_reg_145;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_1_read = temp_kernel_val_2_1_reg_150;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_kernel_val_2_2_read = temp_kernel_val_2_2_reg_155;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_full_n = p_dst_data_stream_0_V_full_n;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_dout = p_src_data_stream_0_V_dout;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_src_data_stream_0_V_empty_n = p_src_data_stream_0_V_empty_n;
assign grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_rows = p_src_rows_V_read;
assign grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start = grp_getStructuringElement_unsigned_char_int_int_3_3_s_fu_56_ap_start_ap_start_reg;
assign p_dst_data_stream_0_V_din = grp_filter_opr_dilate_kernel_0_0_unsigned_char_int_1080_1920_3_3_s_fu_35_p_dst_data_stream_0_V_din;


endmodule //Dilate_0_0_1080_1920_s

