// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Duplicate_1080_1920_16_16_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_rows_V_read,
        src_cols_V_read,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        dst1_rows_V_read,
        dst1_cols_V_read,
        dst1_data_stream_0_V_din,
        dst1_data_stream_0_V_full_n,
        dst1_data_stream_0_V_write,
        dst1_data_stream_1_V_din,
        dst1_data_stream_1_V_full_n,
        dst1_data_stream_1_V_write,
        dst1_data_stream_2_V_din,
        dst1_data_stream_2_V_full_n,
        dst1_data_stream_2_V_write,
        dst2_rows_V_read,
        dst2_cols_V_read,
        dst2_data_stream_0_V_din,
        dst2_data_stream_0_V_full_n,
        dst2_data_stream_0_V_write,
        dst2_data_stream_1_V_din,
        dst2_data_stream_1_V_full_n,
        dst2_data_stream_1_V_write,
        dst2_data_stream_2_V_din,
        dst2_data_stream_2_V_full_n,
        dst2_data_stream_2_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] src_rows_V_read;
input  [11:0] src_cols_V_read;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
input  [11:0] dst1_rows_V_read;
input  [11:0] dst1_cols_V_read;
output  [7:0] dst1_data_stream_0_V_din;
input   dst1_data_stream_0_V_full_n;
output   dst1_data_stream_0_V_write;
output  [7:0] dst1_data_stream_1_V_din;
input   dst1_data_stream_1_V_full_n;
output   dst1_data_stream_1_V_write;
output  [7:0] dst1_data_stream_2_V_din;
input   dst1_data_stream_2_V_full_n;
output   dst1_data_stream_2_V_write;
input  [11:0] dst2_rows_V_read;
input  [11:0] dst2_cols_V_read;
output  [7:0] dst2_data_stream_0_V_din;
input   dst2_data_stream_0_V_full_n;
output   dst2_data_stream_0_V_write;
output  [7:0] dst2_data_stream_1_V_din;
input   dst2_data_stream_1_V_full_n;
output   dst2_data_stream_1_V_write;
output  [7:0] dst2_data_stream_2_V_din;
input   dst2_data_stream_2_V_full_n;
output   dst2_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg src_data_stream_2_V_read;
reg dst1_data_stream_0_V_write;
reg dst1_data_stream_1_V_write;
reg dst1_data_stream_2_V_write;
reg dst2_data_stream_0_V_write;
reg dst2_data_stream_1_V_write;
reg dst2_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [11:0] t_V_3_reg_195;
reg    ap_sig_bdd_72;
wire   [11:0] i_V_fu_212_p2;
reg   [11:0] i_V_reg_242;
wire   [0:0] exitcond_fu_218_p2;
reg   [0:0] exitcond_reg_247;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_114;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [11:0] j_V_fu_223_p2;
wire   [0:0] exitcond6_fu_207_p2;
reg   [11:0] t_V_reg_184;
reg   [1:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_ST_st5_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_true = 1'b1;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond6_fu_207_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_218_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_207_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond_fu_218_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_207_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_218_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & (exitcond_fu_218_p2 == ap_const_lv1_0))) begin
        t_V_3_reg_195 <= j_V_fu_223_p2;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond6_fu_207_p2))) begin
        t_V_3_reg_195 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_72)) begin
        t_V_reg_184 <= ap_const_lv12_0;
    end else if ((ap_ST_st5_fsm_3 == ap_CS_fsm)) begin
        t_V_reg_184 <= i_V_reg_242;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        exitcond_reg_247 <= exitcond_fu_218_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_V_reg_242 <= i_V_fu_212_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or exitcond6_fu_207_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond6_fu_207_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond6_fu_207_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond6_fu_207_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// dst1_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        dst1_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst1_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// dst1_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        dst1_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        dst1_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// dst1_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        dst1_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        dst1_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// dst2_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        dst2_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst2_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// dst2_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        dst2_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        dst2_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// dst2_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        dst2_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        dst2_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_247 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_247 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
        src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_72 or exitcond_fu_218_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_114 or ap_reg_ppiten_pp0_it1 or exitcond6_fu_207_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_72) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond6_fu_207_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_218_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(ap_sig_bdd_114 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~(exitcond_fu_218_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st5_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_st5_fsm_3 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_114 assign process. ///
always @ (src_data_stream_0_V_empty_n or src_data_stream_1_V_empty_n or src_data_stream_2_V_empty_n or dst1_data_stream_0_V_full_n or dst1_data_stream_1_V_full_n or dst1_data_stream_2_V_full_n or dst2_data_stream_0_V_full_n or dst2_data_stream_1_V_full_n or dst2_data_stream_2_V_full_n or exitcond_reg_247)
begin
    ap_sig_bdd_114 = (((src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond_reg_247 == ap_const_lv1_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (src_data_stream_2_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (dst1_data_stream_0_V_full_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (dst1_data_stream_1_V_full_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (dst1_data_stream_2_V_full_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (dst2_data_stream_0_V_full_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (dst2_data_stream_1_V_full_n == ap_const_logic_0)) | ((exitcond_reg_247 == ap_const_lv1_0) & (dst2_data_stream_2_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_72 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_72 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign dst1_data_stream_0_V_din = src_data_stream_0_V_dout;
assign dst1_data_stream_1_V_din = src_data_stream_1_V_dout;
assign dst1_data_stream_2_V_din = src_data_stream_2_V_dout;
assign dst2_data_stream_0_V_din = src_data_stream_0_V_dout;
assign dst2_data_stream_1_V_din = src_data_stream_1_V_dout;
assign dst2_data_stream_2_V_din = src_data_stream_2_V_dout;
assign exitcond6_fu_207_p2 = (t_V_reg_184 == src_rows_V_read? 1'b1: 1'b0);
assign exitcond_fu_218_p2 = (t_V_3_reg_195 == src_cols_V_read? 1'b1: 1'b0);
assign i_V_fu_212_p2 = (t_V_reg_184 + ap_const_lv12_1);
assign j_V_fu_223_p2 = (t_V_3_reg_195 + ap_const_lv12_1);


endmodule //Duplicate_1080_1920_16_16_s

