// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module PaintMask_16_0_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_mask_rows_V_read,
        p_mask_cols_V_read,
        p_mask_data_stream_0_V_dout,
        p_mask_data_stream_0_V_empty_n,
        p_mask_data_stream_0_V_read,
        p_dst_rows_V_read,
        p_dst_cols_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
input  [11:0] p_mask_rows_V_read;
input  [11:0] p_mask_cols_V_read;
input  [7:0] p_mask_data_stream_0_V_dout;
input   p_mask_data_stream_0_V_empty_n;
output   p_mask_data_stream_0_V_read;
input  [11:0] p_dst_rows_V_read;
input  [11:0] p_dst_cols_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_mask_data_stream_0_V_read;
reg[7:0] p_dst_data_stream_0_V_din;
reg p_dst_data_stream_0_V_write;
reg[7:0] p_dst_data_stream_1_V_din;
reg p_dst_data_stream_1_V_write;
reg[7:0] p_dst_data_stream_2_V_din;
reg p_dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
reg   [1:0] ap_CS_fsm = 2'b00;
reg   [11:0] t_V_5_reg_173;
reg    ap_sig_bdd_64;
wire   [11:0] i_V_fu_190_p2;
reg   [11:0] i_V_reg_226;
wire   [0:0] exitcond_fu_196_p2;
reg   [0:0] exitcond_reg_231;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_91;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_reg_231_pp0_it1;
reg   [0:0] tmp_s_reg_255;
reg    ap_sig_bdd_116;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
wire   [11:0] j_V_fu_201_p2;
reg   [7:0] tmp_reg_240;
reg   [7:0] tmp_48_reg_245;
reg   [7:0] tmp_49_reg_250;
wire   [0:0] tmp_s_fu_207_p2;
wire   [0:0] exitcond2_fu_185_p2;
reg   [11:0] t_V_reg_162;
reg   [1:0] ap_NS_fsm;
reg    ap_sig_bdd_214;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 2'b00;
parameter    ap_ST_st2_fsm_1 = 2'b1;
parameter    ap_ST_pp0_stg0_fsm_2 = 2'b10;
parameter    ap_ST_st6_fsm_3 = 2'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_true = 1'b1;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_185_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & ~(exitcond_fu_196_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_185_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & (exitcond_fu_196_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_185_p2)) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & ~(exitcond_fu_196_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_185_p2))) begin
            ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & (exitcond_fu_196_p2 == ap_const_lv1_0))) begin
        t_V_5_reg_173 <= j_V_fu_201_p2;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond2_fu_185_p2))) begin
        t_V_5_reg_173 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~ap_sig_bdd_64)) begin
        t_V_reg_162 <= ap_const_lv12_0;
    end else if ((ap_ST_st6_fsm_3 == ap_CS_fsm)) begin
        t_V_reg_162 <= i_V_reg_226;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        ap_reg_ppstg_exitcond_reg_231_pp0_it1 <= exitcond_reg_231;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        exitcond_reg_231 <= exitcond_fu_196_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_V_reg_226 <= i_V_fu_190_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_231 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        tmp_48_reg_245 <= p_src_data_stream_1_V_dout;
        tmp_49_reg_250 <= p_src_data_stream_2_V_dout;
        tmp_reg_240 <= p_src_data_stream_0_V_dout;
        tmp_s_reg_255 <= tmp_s_fu_207_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_CS_fsm or exitcond2_fu_185_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_185_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond2_fu_185_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond2_fu_185_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// p_dst_data_stream_0_V_din assign process. ///
always @ (tmp_s_reg_255 or tmp_reg_240 or ap_sig_bdd_214)
begin
    if (ap_sig_bdd_214) begin
        if (~(ap_const_lv1_0 == tmp_s_reg_255)) begin
            p_dst_data_stream_0_V_din = tmp_reg_240;
        end else if ((ap_const_lv1_0 == tmp_s_reg_255)) begin
            p_dst_data_stream_0_V_din = ap_const_lv8_FF;
        end else begin
            p_dst_data_stream_0_V_din = ap_const_lv8_FF;
        end
    end else begin
        p_dst_data_stream_0_V_din = ap_const_lv8_FF;
    end
end

/// p_dst_data_stream_0_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_231_pp0_it1 or tmp_s_reg_255 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_lv1_0 == tmp_s_reg_255) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & ~(ap_const_lv1_0 == tmp_s_reg_255) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))))) begin
        p_dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_1_V_din assign process. ///
always @ (tmp_s_reg_255 or tmp_48_reg_245 or ap_sig_bdd_214)
begin
    if (ap_sig_bdd_214) begin
        if (~(ap_const_lv1_0 == tmp_s_reg_255)) begin
            p_dst_data_stream_1_V_din = tmp_48_reg_245;
        end else if ((ap_const_lv1_0 == tmp_s_reg_255)) begin
            p_dst_data_stream_1_V_din = ap_const_lv8_0;
        end else begin
            p_dst_data_stream_1_V_din = ap_const_lv8_0;
        end
    end else begin
        p_dst_data_stream_1_V_din = ap_const_lv8_0;
    end
end

/// p_dst_data_stream_1_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_231_pp0_it1 or tmp_s_reg_255 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_lv1_0 == tmp_s_reg_255) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & ~(ap_const_lv1_0 == tmp_s_reg_255) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))))) begin
        p_dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

/// p_dst_data_stream_2_V_din assign process. ///
always @ (tmp_s_reg_255 or tmp_49_reg_250 or ap_sig_bdd_214)
begin
    if (ap_sig_bdd_214) begin
        if (~(ap_const_lv1_0 == tmp_s_reg_255)) begin
            p_dst_data_stream_2_V_din = tmp_49_reg_250;
        end else if ((ap_const_lv1_0 == tmp_s_reg_255)) begin
            p_dst_data_stream_2_V_din = ap_const_lv8_0;
        end else begin
            p_dst_data_stream_2_V_din = ap_const_lv8_0;
        end
    end else begin
        p_dst_data_stream_2_V_din = ap_const_lv8_0;
    end
end

/// p_dst_data_stream_2_V_write assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_231_pp0_it1 or tmp_s_reg_255 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_lv1_0 == tmp_s_reg_255) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))) | ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & ~(ap_const_lv1_0 == tmp_s_reg_255) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)))))) begin
        p_dst_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

/// p_mask_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_231 or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_231 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        p_mask_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_mask_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_0_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_231 or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_231 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        p_src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_0_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_1_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_231 or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_231 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        p_src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_1_V_read = ap_const_logic_0;
    end
end

/// p_src_data_stream_2_V_read assign process. ///
always @ (ap_CS_fsm or exitcond_reg_231 or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    if (((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (exitcond_reg_231 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))))) begin
        p_src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_64 or exitcond_fu_196_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2 or exitcond2_fu_185_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~ap_sig_bdd_64) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond2_fu_185_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_pp0_stg0_fsm_2 : 
            if ((~((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & ~(exitcond_fu_196_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))) & ~(exitcond_fu_196_p2 == ap_const_lv1_0) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st6_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        ap_ST_st6_fsm_3 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_116 assign process. ///
always @ (p_dst_data_stream_0_V_full_n or p_dst_data_stream_1_V_full_n or p_dst_data_stream_2_V_full_n or ap_reg_ppstg_exitcond_reg_231_pp0_it1 or tmp_s_reg_255)
begin
    ap_sig_bdd_116 = (((p_dst_data_stream_0_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_lv1_0 == tmp_s_reg_255)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_lv1_0 == tmp_s_reg_255) & (p_dst_data_stream_1_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_lv1_0 == tmp_s_reg_255) & (p_dst_data_stream_2_V_full_n == ap_const_logic_0)) | ((p_dst_data_stream_0_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & ~(ap_const_lv1_0 == tmp_s_reg_255)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (p_dst_data_stream_1_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_s_reg_255)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (p_dst_data_stream_2_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_s_reg_255)));
end

/// ap_sig_bdd_214 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_91 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_reg_231_pp0_it1 or ap_sig_bdd_116 or ap_reg_ppiten_pp0_it2)
begin
    ap_sig_bdd_214 = ((ap_ST_pp0_stg0_fsm_2 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_231_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_91 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_116 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2))));
end

/// ap_sig_bdd_64 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_64 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_91 assign process. ///
always @ (p_src_data_stream_0_V_empty_n or p_src_data_stream_1_V_empty_n or p_src_data_stream_2_V_empty_n or p_mask_data_stream_0_V_empty_n or exitcond_reg_231)
begin
    ap_sig_bdd_91 = (((p_src_data_stream_0_V_empty_n == ap_const_logic_0) & (exitcond_reg_231 == ap_const_lv1_0)) | ((exitcond_reg_231 == ap_const_lv1_0) & (p_src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_231 == ap_const_lv1_0) & (p_src_data_stream_2_V_empty_n == ap_const_logic_0)) | ((exitcond_reg_231 == ap_const_lv1_0) & (p_mask_data_stream_0_V_empty_n == ap_const_logic_0)));
end
assign exitcond2_fu_185_p2 = (t_V_reg_162 == p_src_rows_V_read? 1'b1: 1'b0);
assign exitcond_fu_196_p2 = (t_V_5_reg_173 == p_src_cols_V_read? 1'b1: 1'b0);
assign i_V_fu_190_p2 = (t_V_reg_162 + ap_const_lv12_1);
assign j_V_fu_201_p2 = (t_V_5_reg_173 + ap_const_lv12_1);
assign tmp_s_fu_207_p2 = (p_mask_data_stream_0_V_dout == ap_const_lv8_0? 1'b1: 1'b0);


endmodule //PaintMask_16_0_1080_1920_s

